import type { Tables } from "@/utils/supabase/database.types";

// Types matching Supabase schema exactly
export type CandidateRow = Tables<"candidates">;
export type CalendarEventRow = Tables<"calendar_events">;
export type PlanRow = Tables<"plans">;
export type VotingLocationRow = Tables<"voting_locations">;
export type MesaLocationRow = Tables<"mesa_locations">;
export type MesaScheduleRow = Tables<"mesa_schedule">;

// Extended types for frontend use (with relationships)
export type VotingLocationWithMesa = VotingLocationRow & {
  mesas?: MesaLocationRow[];
};

export type MesaLocationWithVoting = MesaLocationRow & {
  voting_location?: VotingLocationRow;
};

// Dummy data matching Supabase schema exactly
export const dummyCandidates: CandidateRow[] = [
  {
    id: "1",
    nombre: "Juan Pérez García",
    partido: "Partido Democrático Nacional",
    region: "Lima",
    cargo: "Presidente",
    hoja_vida:
      "Economista con 20 años de experiencia en el sector público. Magíster en Políticas Públicas por la Universidad Nacional. Ex Ministro de Economía con amplia trayectoria en gestión fiscal y desarrollo económico.",
    actividades: [
      "Ex Ministro de Economía (2018-2020)",
      "Consultor internacional en desarrollo económico",
      "Profesor universitario en economía aplicada",
      "Autor de 5 libros sobre política económica",
    ] as unknown as Tables<"candidates">["actividades"],
    propuestas: [
      "Reforma tributaria progresiva",
      "Inversión en infraestructura rural",
      "Modernización del sistema de salud",
      "Fortalecimiento de la educación técnica",
      "Descentralización fiscal",
    ] as unknown as Tables<"candidates">["propuestas"],
    imagen_url: null,
    numero_lista: 1,
    orden: 1,
    tipo_candidato: "Presidencial",
    created_at: "2025-12-01T10:00:00Z",
    updated_at: "2026-01-15T14:30:00Z",
  },
  {
    id: "2",
    nombre: "María López Sánchez",
    partido: "Frente por el Cambio",
    region: "Arequipa",
    cargo: "Presidente",
    hoja_vida:
      "Abogada especializada en derechos humanos. Doctora en Derecho Constitucional con experiencia en organismos internacionales. Defensora de los derechos fundamentales y la transparencia.",
    actividades: [
      "Defensora del Pueblo Regional (2015-2019)",
      "Asesora en la Comisión Interamericana de DDHH",
      "Fundadora de ONG de transparencia",
      "Consultora en reforma judicial",
    ] as unknown as Tables<"candidates">["actividades"],
    propuestas: [
      "Reforma del sistema de justicia",
      "Ley de transparencia y anticorrupción",
      "Protección de comunidades indígenas",
      "Igualdad de género en el sector público",
      "Fortalecimiento del Estado de derecho",
    ] as unknown as Tables<"candidates">["propuestas"],
    imagen_url: null,
    numero_lista: 2,
    orden: 1,
    tipo_candidato: "Presidencial",
    created_at: "2025-12-02T10:00:00Z",
    updated_at: "2026-01-16T14:30:00Z",
  },
  {
    id: "3",
    nombre: "Carlos Rodríguez Mendoza",
    partido: "Alianza Popular",
    region: "Cusco",
    cargo: "Presidente",
    hoja_vida:
      "Empresario agrícola y líder comunitario. Ingeniero agrónomo con experiencia en desarrollo sostenible. Promotor de la agricultura orgánica y el desarrollo rural.",
    actividades: [
      "Presidente de la Federación Agraria Regional",
      "Coordinador de proyectos de agricultura sostenible",
      "Gestor de cooperativas rurales",
      "Asesor en políticas agrícolas",
    ] as unknown as Tables<"candidates">["actividades"],
    propuestas: [
      "Apoyo integral al agro peruano",
      "Tecnificación del campo",
      "Seguridad alimentaria nacional",
      "Protección del medio ambiente",
      "Desarrollo rural sostenible",
    ] as unknown as Tables<"candidates">["propuestas"],
    imagen_url: null,
    numero_lista: 3,
    orden: 1,
    tipo_candidato: "Presidencial",
    created_at: "2025-12-03T10:00:00Z",
    updated_at: "2026-01-17T14:30:00Z",
  },
  {
    id: "4",
    nombre: "Ana Torres Villalobos",
    partido: "Movimiento Ciudadano",
    region: "Piura",
    cargo: "Presidente",
    hoja_vida:
      "Médica cirujana con especialización en salud pública. Ha trabajado en zonas rurales y marginadas durante 15 años. Experta en gestión hospitalaria y salud preventiva.",
    actividades: [
      "Directora de Hospital Regional (2016-2021)",
      "Coordinadora de programas de vacunación",
      "Activista en salud preventiva",
      "Consultora en salud pública internacional",
    ] as unknown as Tables<"candidates">["actividades"],
    propuestas: [
      "Salud universal y gratuita",
      "Prevención de enfermedades tropicales",
      "Fortalecimiento de hospitales regionales",
      "Salud mental como prioridad",
      "Sistema de salud descentralizado",
    ] as unknown as Tables<"candidates">["propuestas"],
    imagen_url: null,
    numero_lista: 4,
    orden: 1,
    tipo_candidato: "Presidencial",
    created_at: "2025-12-04T10:00:00Z",
    updated_at: "2026-01-18T14:30:00Z",
  },
  {
    id: "5",
    nombre: "Roberto Flores Castro",
    partido: "Partido del Progreso",
    region: "La Libertad",
    cargo: "Presidente",
    hoja_vida:
      "Ingeniero industrial con maestría en gestión pública. Experiencia en modernización del Estado. Líder en transformación digital y gobierno electrónico.",
    actividades: [
      "Viceministro de Innovación Tecnológica",
      "Consultor en transformación digital",
      "Fundador de startup tecnológica",
      "Asesor en gobierno electrónico",
    ] as unknown as Tables<"candidates">["actividades"],
    propuestas: [
      "Digitalización del Estado",
      "Impulso a la innovación y startups",
      "Conectividad en zonas rurales",
      "Educación digital desde primaria",
      "Gobierno electrónico integral",
    ] as unknown as Tables<"candidates">["propuestas"],
    imagen_url: null,
    numero_lista: 5,
    orden: 1,
    tipo_candidato: "Presidencial",
    created_at: "2025-12-05T10:00:00Z",
    updated_at: "2026-01-19T14:30:00Z",
  },
  {
    id: "6",
    nombre: "Patricia Ramírez Luna",
    partido: "Unión Nacional",
    region: "Lambayeque",
    cargo: "Congresista",
    hoja_vida:
      "Contadora pública y auditora. Especialista en gestión fiscal y control gubernamental. Experta en auditoría y control de gestión pública.",
    actividades: [
      "Auditora en la Contraloría General",
      "Consultora en gestión financiera",
      "Docente en finanzas públicas",
      "Asesora en control gubernamental",
    ] as unknown as Tables<"candidates">["actividades"],
    propuestas: [
      "Austeridad en el gasto público",
      "Control estricto del presupuesto",
      "Reducción de burocracia estatal",
      "Transparencia fiscal",
    ] as unknown as Tables<"candidates">["propuestas"],
    imagen_url: null,
    numero_lista: 1,
    orden: 1,
    tipo_candidato: "Congresal",
    created_at: "2025-12-06T10:00:00Z",
    updated_at: "2026-01-20T14:30:00Z",
  },
  {
    id: "7",
    nombre: "Luis Vargas Herrera",
    partido: "Frente Amplio",
    region: "Junín",
    cargo: "Congresista",
    hoja_vida:
      "Sociólogo con doctorado en ciencias políticas. Investigador en desigualdad social. Autor de múltiples estudios sobre pobreza y exclusión.",
    actividades: [
      "Investigador principal en instituto de estudios sociales",
      "Asesor parlamentario en comisión de inclusión social",
      "Autor de libros sobre pobreza en el Perú",
      "Consultor en políticas sociales",
    ] as unknown as Tables<"candidates">["actividades"],
    propuestas: [
      "Reducción de la desigualdad económica",
      "Programas sociales focalizados",
      "Reconocimiento de derechos laborales",
      "Inclusión social integral",
    ] as unknown as Tables<"candidates">["propuestas"],
    imagen_url: null,
    numero_lista: 2,
    orden: 1,
    tipo_candidato: "Congresal",
    created_at: "2025-12-07T10:00:00Z",
    updated_at: "2026-01-21T14:30:00Z",
  },
  {
    id: "8",
    nombre: "Sandra Morales Díaz",
    partido: "Renovación Nacional",
    region: "Tacna",
    cargo: "Congresista",
    hoja_vida:
      "Periodista y comunicadora social. Especializada en investigación de corrupción. Ganadora de premios internacionales de periodismo.",
    actividades: [
      "Directora de medio de comunicación independiente",
      "Ganadora de premio de periodismo de investigación",
      "Activista por la libertad de prensa",
      "Consultora en comunicación política",
    ] as unknown as Tables<"candidates">["actividades"],
    propuestas: [
      "Ley de protección a periodistas",
      "Transparencia en medios públicos",
      "Acceso a información gubernamental",
      "Fortalecimiento de la prensa libre",
    ] as unknown as Tables<"candidates">["propuestas"],
    imagen_url: null,
    numero_lista: 3,
    orden: 1,
    tipo_candidato: "Congresal",
    created_at: "2025-12-08T10:00:00Z",
    updated_at: "2026-01-22T14:30:00Z",
  },
  {
    id: "9",
    nombre: "Miguel Ángel Cruz Rojas",
    partido: "Partido Verde",
    region: "Ucayali",
    cargo: "Congresista",
    hoja_vida:
      "Biólogo y ambientalista. Defensor de la Amazonía y los recursos naturales. Experto en conservación y desarrollo sostenible.",
    actividades: [
      "Director de ONG de conservación amazónica",
      "Coordinador de proyectos de reforestación",
      "Asesor técnico en políticas ambientales",
      "Investigador en biodiversidad",
    ] as unknown as Tables<"candidates">["actividades"],
    propuestas: [
      "Protección legal de la Amazonía",
      "Combate a la deforestación ilegal",
      "Energías renovables",
      "Conservación de recursos naturales",
    ] as unknown as Tables<"candidates">["propuestas"],
    imagen_url: null,
    numero_lista: 4,
    orden: 1,
    tipo_candidato: "Congresal",
    created_at: "2025-12-09T10:00:00Z",
    updated_at: "2026-01-23T14:30:00Z",
  },
  {
    id: "10",
    nombre: "Elena Gutiérrez Paredes",
    partido: "Fuerza Ciudadana",
    region: "Ica",
    cargo: "Congresista",
    hoja_vida:
      "Profesora de educación secundaria. Activista por la mejora de la calidad educativa. Líder sindical y promotora de reformas educativas.",
    actividades: [
      "Secretaria General del Sindicato de Docentes",
      "Coordinadora de programas de capacitación docente",
      "Impulsora de reforma educativa regional",
      "Consultora en políticas educativas",
    ] as unknown as Tables<"candidates">["actividades"],
    propuestas: [
      "Aumento del presupuesto educativo",
      "Mejor remuneración para docentes",
      "Infraestructura escolar de calidad",
      "Reforma curricular integral",
    ] as unknown as Tables<"candidates">["propuestas"],
    imagen_url: null,
    numero_lista: 5,
    orden: 1,
    tipo_candidato: "Congresal",
    created_at: "2025-12-10T10:00:00Z",
    updated_at: "2026-01-24T14:30:00Z",
  },
  {
    id: "11",
    nombre: "Fernando Quispe Huamán",
    partido: "Partido Democrático Nacional",
    region: "Lima",
    cargo: "Congresista",
    hoja_vida:
      "Abogado constitucionalista con maestría en derecho público. Especialista en reforma del Estado y descentralización.",
    actividades: [
      "Asesor constitucional en el Congreso",
      "Profesor de derecho constitucional",
      "Consultor en reforma del Estado",
      "Autor de estudios sobre descentralización",
    ] as unknown as Tables<"candidates">["actividades"],
    propuestas: [
      "Reforma constitucional",
      "Descentralización efectiva",
      "Fortalecimiento de gobiernos regionales",
      "Modernización del Estado",
    ] as unknown as Tables<"candidates">["propuestas"],
    imagen_url: null,
    numero_lista: 1,
    orden: 2,
    tipo_candidato: "Congresal",
    created_at: "2025-12-11T10:00:00Z",
    updated_at: "2026-01-25T14:30:00Z",
  },
  {
    id: "12",
    nombre: "Carmen Silva Rojas",
    partido: "Frente por el Cambio",
    region: "Arequipa",
    cargo: "Congresista",
    hoja_vida:
      "Ingeniera de sistemas con especialización en ciberseguridad. Experta en protección de datos y privacidad digital.",
    actividades: [
      "Directora de seguridad informática",
      "Consultora en ciberseguridad",
      "Investigadora en protección de datos",
      "Asesora en políticas digitales",
    ] as unknown as Tables<"candidates">["actividades"],
    propuestas: [
      "Ley de protección de datos personales",
      "Ciberseguridad nacional",
      "Gobierno digital seguro",
      "Educación en seguridad informática",
    ] as unknown as Tables<"candidates">["propuestas"],
    imagen_url: null,
    numero_lista: 2,
    orden: 2,
    tipo_candidato: "Congresal",
    created_at: "2025-12-12T10:00:00Z",
    updated_at: "2026-01-26T14:30:00Z",
  },
];

export const dummyCalendarEvents: CalendarEventRow[] = [
  {
    id: "1",
    fecha: "2026-01-15",
    descripcion:
      "Inicio del periodo de inscripción de candidatos presidenciales y congresales",
    tipo: "inscripcion",
    importante: true,
    created_at: "2025-12-01T10:00:00Z",
    updated_at: "2026-01-10T14:30:00Z",
  },
  {
    id: "2",
    fecha: "2026-02-28",
    descripcion: "Cierre de inscripciones y presentación de planes de gobierno",
    tipo: "inscripcion",
    importante: true,
    created_at: "2025-12-01T10:00:00Z",
    updated_at: "2026-01-10T14:30:00Z",
  },
  {
    id: "3",
    fecha: "2026-03-15",
    descripcion: "Primer debate presidencial nacional - Temas generales",
    tipo: "debate",
    importante: true,
    created_at: "2025-12-01T10:00:00Z",
    updated_at: "2026-01-10T14:30:00Z",
  },
  {
    id: "4",
    fecha: "2026-03-25",
    descripcion: "Segundo debate presidencial - Temas económicos y sociales",
    tipo: "debate",
    importante: true,
    created_at: "2025-12-01T10:00:00Z",
    updated_at: "2026-01-10T14:30:00Z",
  },
  {
    id: "5",
    fecha: "2026-04-05",
    descripcion: "Tercer debate presidencial - Temas de política exterior",
    tipo: "debate",
    importante: false,
    created_at: "2025-12-01T10:00:00Z",
    updated_at: "2026-01-10T14:30:00Z",
  },
  {
    id: "6",
    fecha: "2026-04-11",
    descripcion: "Primera vuelta electoral - Elecciones generales",
    tipo: "votacion",
    importante: true,
    created_at: "2025-12-01T10:00:00Z",
    updated_at: "2026-01-10T14:30:00Z",
  },
  {
    id: "7",
    fecha: "2026-06-05",
    descripcion: "Segunda vuelta electoral (si es necesaria)",
    tipo: "votacion",
    importante: true,
    created_at: "2025-12-01T10:00:00Z",
    updated_at: "2026-01-10T14:30:00Z",
  },
  {
    id: "8",
    fecha: "2026-06-20",
    descripcion: "Proclamación oficial de resultados electorales",
    tipo: "proclamacion",
    importante: true,
    created_at: "2025-12-01T10:00:00Z",
    updated_at: "2026-01-10T14:30:00Z",
  },
  {
    id: "9",
    fecha: "2026-07-28",
    descripcion: "Asunción del nuevo gobierno y toma de mando",
    tipo: "otro",
    importante: true,
    created_at: "2025-12-01T10:00:00Z",
    updated_at: "2026-01-10T14:30:00Z",
  },
  {
    id: "10",
    fecha: "2026-01-20",
    descripcion: "Presentación de listas de candidatos al JNE",
    tipo: "inscripcion",
    importante: false,
    created_at: "2025-12-01T10:00:00Z",
    updated_at: "2026-01-10T14:30:00Z",
  },
  {
    id: "11",
    fecha: "2026-02-10",
    descripcion: "Inicio de campaña electoral",
    tipo: "otro",
    importante: true,
    created_at: "2025-12-01T10:00:00Z",
    updated_at: "2026-01-10T14:30:00Z",
  },
  {
    id: "12",
    fecha: "2026-04-09",
    descripcion: "Veda electoral - Fin de campaña",
    tipo: "otro",
    importante: true,
    created_at: "2025-12-01T10:00:00Z",
    updated_at: "2026-01-10T14:30:00Z",
  },
];

export const dummyPlans: PlanRow[] = [
  {
    id: "1",
    partido: "Partido Democrático Nacional",
    resumen_ia:
      "El plan se enfoca en la reactivación económica mediante una reforma tributaria progresiva y la inversión pública en infraestructura. Propone modernizar el sistema de salud con hospitales regionales y fortalecer la educación técnica para reducir la brecha laboral. Incluye medidas de descentralización fiscal y apoyo a la pequeña y mediana empresa. El plan contempla una inversión de 50 mil millones de soles en infraestructura durante los primeros 3 años.",
    temas_principales: [
      "Economía y empleo",
      "Salud pública",
      "Educación técnica",
      "Descentralización",
      "Infraestructura",
    ] as unknown as Tables<"plans">["temas_principales"],
    fecha_publicacion: "2026-02-20",
    url_documento: "https://example.com/planes/pdn-2026.pdf",
    created_at: "2026-02-20T10:00:00Z",
    updated_at: "2026-02-20T10:00:00Z",
  },
  {
    id: "2",
    partido: "Frente por el Cambio",
    resumen_ia:
      "El plan prioriza la reforma del sistema de justicia con mecanismos de transparencia y anticorrupción. Plantea la protección de derechos humanos y comunidades indígenas mediante leyes específicas. Propone paridad de género en cargos públicos y una reforma constitucional para fortalecer el Estado de derecho. Incluye la creación de una comisión independiente anticorrupción con poderes amplios.",
    temas_principales: [
      "Justicia y anticorrupción",
      "Derechos humanos",
      "Igualdad de género",
      "Reforma constitucional",
      "Transparencia",
    ] as unknown as Tables<"plans">["temas_principales"],
    fecha_publicacion: "2026-02-18",
    url_documento: "https://example.com/planes/fpc-2026.pdf",
    created_at: "2026-02-18T10:00:00Z",
    updated_at: "2026-02-18T10:00:00Z",
  },
  {
    id: "3",
    partido: "Alianza Popular",
    resumen_ia:
      "Centrado en el desarrollo agrícola sostenible y la seguridad alimentaria. Propone tecnificación del campo, créditos blandos para agricultores y protección de ecosistemas naturales. Incluye programas de reforestación y gestión responsable del agua en zonas rurales. El plan busca duplicar la producción agrícola en 5 años mediante tecnología e inversión.",
    temas_principales: [
      "Agricultura sostenible",
      "Seguridad alimentaria",
      "Medio ambiente",
      "Desarrollo rural",
      "Recursos hídricos",
    ] as unknown as Tables<"plans">["temas_principales"],
    fecha_publicacion: "2026-02-22",
    url_documento: "https://example.com/planes/ap-2026.pdf",
    created_at: "2026-02-22T10:00:00Z",
    updated_at: "2026-02-22T10:00:00Z",
  },
  {
    id: "4",
    partido: "Movimiento Ciudadano",
    resumen_ia:
      "El plan garantiza salud universal y gratuita con énfasis en prevención de enfermedades. Propone fortalecimiento de hospitales regionales, brigadas médicas itinerantes y atención prioritaria en salud mental. Incluye programas de vacunación masiva y control de enfermedades tropicales. Busca reducir la mortalidad materna e infantil en un 40% durante el primer quinquenio.",
    temas_principales: [
      "Salud universal",
      "Prevención de enfermedades",
      "Salud mental",
      "Hospitales regionales",
      "Salud preventiva",
    ] as unknown as Tables<"plans">["temas_principales"],
    fecha_publicacion: "2026-02-25",
    url_documento: "https://example.com/planes/mc-2026.pdf",
    created_at: "2026-02-25T10:00:00Z",
    updated_at: "2026-02-25T10:00:00Z",
  },
  {
    id: "5",
    partido: "Partido del Progreso",
    resumen_ia:
      "Enfocado en la transformación digital del Estado y la conectividad nacional. Propone digitalización de trámites, gobierno electrónico y acceso a internet en zonas rurales. Incluye incentivos para startups, educación digital desde la primaria y creación de hubs tecnológicos regionales. El plan busca que el 90% de trámites estatales sean digitales para 2028.",
    temas_principales: [
      "Transformación digital",
      "Innovación tecnológica",
      "Conectividad",
      "Educación digital",
      "Gobierno electrónico",
    ] as unknown as Tables<"plans">["temas_principales"],
    fecha_publicacion: "2026-02-27",
    url_documento: "https://example.com/planes/pp-2026.pdf",
    created_at: "2026-02-27T10:00:00Z",
    updated_at: "2026-02-27T10:00:00Z",
  },
  {
    id: "6",
    partido: "Unión Nacional",
    resumen_ia:
      "Plan enfocado en la austeridad fiscal y el control del gasto público. Propone reducción de la burocracia estatal, optimización de recursos y transparencia en el manejo presupuestal. Incluye medidas de control y auditoría continua de las finanzas públicas.",
    temas_principales: [
      "Austeridad fiscal",
      "Control del gasto",
      "Transparencia",
      "Optimización de recursos",
    ] as unknown as Tables<"plans">["temas_principales"],
    fecha_publicacion: "2026-02-24",
    url_documento: "https://example.com/planes/un-2026.pdf",
    created_at: "2026-02-24T10:00:00Z",
    updated_at: "2026-02-24T10:00:00Z",
  },
  {
    id: "7",
    partido: "Frente Amplio",
    resumen_ia:
      "Plan centrado en la reducción de la desigualdad y la inclusión social. Propone programas sociales focalizados, reconocimiento de derechos laborales y políticas de redistribución. Incluye medidas para combatir la pobreza extrema y mejorar el acceso a servicios básicos.",
    temas_principales: [
      "Reducción de desigualdad",
      "Inclusión social",
      "Derechos laborales",
      "Programas sociales",
    ] as unknown as Tables<"plans">["temas_principales"],
    fecha_publicacion: "2026-02-26",
    url_documento: "https://example.com/planes/fa-2026.pdf",
    created_at: "2026-02-26T10:00:00Z",
    updated_at: "2026-02-26T10:00:00Z",
  },
  {
    id: "8",
    partido: "Partido Verde",
    resumen_ia:
      "Plan ambientalista enfocado en la protección de la Amazonía y los recursos naturales. Propone combate a la deforestación ilegal, energías renovables y conservación de la biodiversidad. Incluye programas de reforestación y gestión sostenible de recursos.",
    temas_principales: [
      "Protección ambiental",
      "Conservación",
      "Energías renovables",
      "Biodiversidad",
    ] as unknown as Tables<"plans">["temas_principales"],
    fecha_publicacion: "2026-02-23",
    url_documento: "https://example.com/planes/pv-2026.pdf",
    created_at: "2026-02-23T10:00:00Z",
    updated_at: "2026-02-23T10:00:00Z",
  },
];

export const sampleEmbeddings = [
  {
    content:
      "Las elecciones generales de 2026 se realizarán el 11 de abril en primera vuelta. Los candidatos deben inscribirse entre enero y febrero.",
    category: "calendario",
  },
  {
    content:
      "Juan Pérez García es economista y propone una reforma tributaria progresiva como parte de su plan de gobierno.",
    category: "candidatos",
  },
  {
    content:
      "María López Sánchez es abogada especializada en derechos humanos y plantea una reforma del sistema de justicia.",
    category: "candidatos",
  },
  {
    content:
      "El debate presidencial sobre temas económicos se realizará el 25 de marzo de 2026.",
    category: "calendario",
  },
  {
    content:
      "Los planes de gobierno deben ser presentados antes del cierre de inscripciones el 28 de febrero.",
    category: "proceso",
  },
];

export const dummyVotingLocations: VotingLocationRow[] = [
  {
    id: "1",
    name: "Colegio Nacional San José",
    address: "Av. Brasil 1234, Magdalena del Mar",
    latitude: -12.0969,
    longitude: -77.08,
    district: "Magdalena del Mar",
    created_at: "2025-11-01T10:00:00Z",
    updated_at: "2026-01-15T14:30:00Z",
  },
  {
    id: "2",
    name: "Instituto Educativo Los Olivos",
    address: "Jr. Los Olivos 567, Los Olivos",
    latitude: -11.9833,
    longitude: -77.0667,
    district: "Los Olivos",
    created_at: "2025-11-01T10:00:00Z",
    updated_at: "2026-01-15T14:30:00Z",
  },
  {
    id: "3",
    name: "Escuela Primaria San Martín",
    address: "Av. San Martín 890, San Martín de Porres",
    latitude: -11.9667,
    longitude: -77.0833,
    district: "San Martín de Porres",
    created_at: "2025-11-01T10:00:00Z",
    updated_at: "2026-01-15T14:30:00Z",
  },
  {
    id: "4",
    name: "Colegio Secundario La Victoria",
    address: "Av. La Victoria 234, La Victoria",
    latitude: -12.0667,
    longitude: -77.0167,
    district: "La Victoria",
    created_at: "2025-11-01T10:00:00Z",
    updated_at: "2026-01-15T14:30:00Z",
  },
  {
    id: "5",
    name: "Centro Educativo Miraflores",
    address: "Av. Larco 1456, Miraflores",
    latitude: -12.1167,
    longitude: -77.0333,
    district: "Miraflores",
    created_at: "2025-11-01T10:00:00Z",
    updated_at: "2026-01-15T14:30:00Z",
  },
  {
    id: "6",
    name: "Instituto San Isidro",
    address: "Jr. Las Begonias 789, San Isidro",
    latitude: -12.1,
    longitude: -77.0333,
    district: "San Isidro",
    created_at: "2025-11-01T10:00:00Z",
    updated_at: "2026-01-15T14:30:00Z",
  },
  {
    id: "7",
    name: "Colegio Nacional Surco",
    address: "Av. Benavides 321, Santiago de Surco",
    latitude: -12.1333,
    longitude: -76.9833,
    district: "Santiago de Surco",
    created_at: "2025-11-01T10:00:00Z",
    updated_at: "2026-01-15T14:30:00Z",
  },
  {
    id: "8",
    name: "Escuela Primaria Chorrillos",
    address: "Av. Defensores del Morro 654, Chorrillos",
    latitude: -12.1667,
    longitude: -77.0167,
    district: "Chorrillos",
    created_at: "2025-11-01T10:00:00Z",
    updated_at: "2026-01-15T14:30:00Z",
  },
  {
    id: "9",
    name: "Colegio Nacional Breña",
    address: "Av. Venezuela 123, Breña",
    latitude: -12.05,
    longitude: -77.05,
    district: "Breña",
    created_at: "2025-11-01T10:00:00Z",
    updated_at: "2026-01-15T14:30:00Z",
  },
  {
    id: "10",
    name: "Instituto Educativo Rímac",
    address: "Jr. Trujillo 456, Rímac",
    latitude: -12.0333,
    longitude: -77.0167,
    district: "Rímac",
    created_at: "2025-11-01T10:00:00Z",
    updated_at: "2026-01-15T14:30:00Z",
  },
  {
    id: "11",
    name: "Escuela Secundaria Callao",
    address: "Av. Grau 789, Callao",
    latitude: -12.0667,
    longitude: -77.1333,
    district: "Callao",
    created_at: "2025-11-01T10:00:00Z",
    updated_at: "2026-01-15T14:30:00Z",
  },
  {
    id: "12",
    name: "Colegio Nacional Barranco",
    address: "Av. Grau 321, Barranco",
    latitude: -12.15,
    longitude: -77.0167,
    district: "Barranco",
    created_at: "2025-11-01T10:00:00Z",
    updated_at: "2026-01-15T14:30:00Z",
  },
];

export const dummyMesaLocations: MesaLocationRow[] = [
  {
    id: "1",
    mesa_number: "1234",
    local_id: "1",
    pavilion: "A",
    floor: "1",
    room: "101",
    created_at: "2025-11-15T10:00:00Z",
    updated_at: "2026-01-20T14:30:00Z",
  },
  {
    id: "2",
    mesa_number: "1235",
    local_id: "1",
    pavilion: "A",
    floor: "1",
    room: "102",
    created_at: "2025-11-15T10:00:00Z",
    updated_at: "2026-01-20T14:30:00Z",
  },
  {
    id: "3",
    mesa_number: "1236",
    local_id: "1",
    pavilion: "B",
    floor: "1",
    room: "201",
    created_at: "2025-11-15T10:00:00Z",
    updated_at: "2026-01-20T14:30:00Z",
  },
  {
    id: "4",
    mesa_number: "1237",
    local_id: "1",
    pavilion: "B",
    floor: "2",
    room: "202",
    created_at: "2025-11-15T10:00:00Z",
    updated_at: "2026-01-20T14:30:00Z",
  },
  {
    id: "5",
    mesa_number: "2345",
    local_id: "2",
    pavilion: "Principal",
    floor: "1",
    room: "15",
    created_at: "2025-11-15T10:00:00Z",
    updated_at: "2026-01-20T14:30:00Z",
  },
  {
    id: "6",
    mesa_number: "2346",
    local_id: "2",
    pavilion: "Principal",
    floor: "2",
    room: "25",
    created_at: "2025-11-15T10:00:00Z",
    updated_at: "2026-01-20T14:30:00Z",
  },
  {
    id: "7",
    mesa_number: "2347",
    local_id: "2",
    pavilion: "Secundario",
    floor: "1",
    room: "30",
    created_at: "2025-11-15T10:00:00Z",
    updated_at: "2026-01-20T14:30:00Z",
  },
  {
    id: "8",
    mesa_number: "3456",
    local_id: "3",
    pavilion: "Norte",
    floor: "1",
    room: "5",
    created_at: "2025-11-15T10:00:00Z",
    updated_at: "2026-01-20T14:30:00Z",
  },
  {
    id: "9",
    mesa_number: "3457",
    local_id: "3",
    pavilion: "Sur",
    floor: "1",
    room: "6",
    created_at: "2025-11-15T10:00:00Z",
    updated_at: "2026-01-20T14:30:00Z",
  },
  {
    id: "10",
    mesa_number: "3458",
    local_id: "3",
    pavilion: "Norte",
    floor: "2",
    room: "15",
    created_at: "2025-11-15T10:00:00Z",
    updated_at: "2026-01-20T14:30:00Z",
  },
  {
    id: "11",
    mesa_number: "4567",
    local_id: "4",
    pavilion: "A",
    floor: "1",
    room: "10",
    created_at: "2025-11-15T10:00:00Z",
    updated_at: "2026-01-20T14:30:00Z",
  },
  {
    id: "12",
    mesa_number: "4568",
    local_id: "4",
    pavilion: "B",
    floor: "2",
    room: "20",
    created_at: "2025-11-15T10:00:00Z",
    updated_at: "2026-01-20T14:30:00Z",
  },
  {
    id: "13",
    mesa_number: "5678",
    local_id: "5",
    pavilion: "Principal",
    floor: "1",
    room: "1",
    created_at: "2025-11-15T10:00:00Z",
    updated_at: "2026-01-20T14:30:00Z",
  },
  {
    id: "14",
    mesa_number: "5679",
    local_id: "5",
    pavilion: "Principal",
    floor: "1",
    room: "2",
    created_at: "2025-11-15T10:00:00Z",
    updated_at: "2026-01-20T14:30:00Z",
  },
  {
    id: "15",
    mesa_number: "5680",
    local_id: "5",
    pavilion: "Secundario",
    floor: "1",
    room: "5",
    created_at: "2025-11-15T10:00:00Z",
    updated_at: "2026-01-20T14:30:00Z",
  },
  {
    id: "16",
    mesa_number: "6789",
    local_id: "6",
    pavilion: "A",
    floor: "1",
    room: "101",
    created_at: "2025-11-15T10:00:00Z",
    updated_at: "2026-01-20T14:30:00Z",
  },
  {
    id: "17",
    mesa_number: "6790",
    local_id: "6",
    pavilion: "A",
    floor: "2",
    room: "201",
    created_at: "2025-11-15T10:00:00Z",
    updated_at: "2026-01-20T14:30:00Z",
  },
  {
    id: "18",
    mesa_number: "7890",
    local_id: "7",
    pavilion: "Principal",
    floor: "1",
    room: "10",
    created_at: "2025-11-15T10:00:00Z",
    updated_at: "2026-01-20T14:30:00Z",
  },
  {
    id: "19",
    mesa_number: "7891",
    local_id: "7",
    pavilion: "Principal",
    floor: "1",
    room: "11",
    created_at: "2025-11-15T10:00:00Z",
    updated_at: "2026-01-20T14:30:00Z",
  },
  {
    id: "20",
    mesa_number: "8901",
    local_id: "8",
    pavilion: "Norte",
    floor: "1",
    room: "5",
    created_at: "2025-11-15T10:00:00Z",
    updated_at: "2026-01-20T14:30:00Z",
  },
];

export const dummyMesaSchedule: MesaScheduleRow[] = [
  {
    id: "1",
    phase: "instalacion",
    start_time: "2026-04-11T06:00:00-05:00",
    end_time: "2026-04-11T07:00:00-05:00",
    description:
      "Instalación de la mesa electoral. Verificación de materiales y preparación del espacio de votación. Los miembros de mesa deben llegar puntualmente a las 6:00 AM para verificar que todos los materiales estén completos y en buen estado.",
    created_at: "2025-12-01T10:00:00Z",
    updated_at: "2026-01-15T14:30:00Z",
  },
  {
    id: "2",
    phase: "sufragio",
    start_time: "2026-04-11T07:00:00-05:00",
    end_time: "2026-04-11T16:00:00-05:00",
    description:
      "Proceso de sufragio. Supervisión del proceso de votación, verificación de identidad de electores y entrega de cédulas. Los electores pueden votar desde las 7:00 AM hasta las 4:00 PM. Se debe verificar la identidad de cada elector y asegurar que vote en secreto.",
    created_at: "2025-12-01T10:00:00Z",
    updated_at: "2026-01-15T14:30:00Z",
  },
  {
    id: "3",
    phase: "conteo",
    start_time: "2026-04-11T16:00:00-05:00",
    end_time: "2026-04-11T20:00:00-05:00",
    description:
      "Escrutinio de votos. Conteo de votos, llenado de actas y entrega de resultados a las autoridades competentes. Una vez cerrada la votación, se procede al conteo público de los votos. Los resultados se registran en las actas correspondientes y se entregan a las autoridades del JNE.",
    created_at: "2025-12-01T10:00:00Z",
    updated_at: "2026-01-15T14:30:00Z",
  },
];

// Backward compatibility exports (deprecated - use dummy* prefixed exports)
export const candidates = dummyCandidates;
export const calendarEvents = dummyCalendarEvents;
export const plans = dummyPlans;
